# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dinh V. Le
email: dinh.v.le@gmail.com
description: >
  on learning and programming
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dinhvle.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Dinh V. Le'
bio: >
  Tinkerer, life-long learner, amateur ukulele player and aspiring polymath.
  Currently at Galvanize learning web development.
author_image: "/assets/images/author.jpg"
twitter_username: dinhvle
github_username:  dinhvle
linkedin_username: dinhvle

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
